# jenkins-infra.yml
services:
  jenkins:
    build: 
      context: jenkins
      dockerfile: Dockerfile
    # image: jenkins/jenkins:lts ## custom dockerfile
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms512m"
    container_name: jenkins
    # ports:
      # -  "8080:8080"
      ## ports sostituito da CF tunnel raggiungibile su jenkins.alematta.com protetto da PIN
    networks:
      - web_net
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # DooD
    restart: always

  cloudflared:
    env_file: ".env"
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-infra
    networks:
      - web_net
    command: tunnel --no-autoupdate run --token ${CFTI}
    restart: always

volumes:
  jenkins_home:

networks:
  web_net:
    external: true 

# steps and commands for first run:
# Run 'docker network create web_net' to create the network
# Start compose with 'docker compose -f docker-compose.jenkins-infra.yml up -d --build'

  