pipeline {
    agent any
    environment {
        CR_PAT = credentials('GHCR_TOKEN')
        GH_USER = 'almat101'
        // jenkins-migration-auth-service
    }
    stages {
        stage('Checking SHA') {
            steps {
                echo 'Commit SHA: ${GIT_COMMIT}'
            }
        }
        stage('build auth-service') {
            steps {
                echo 'Building auth-service with tag(sha)...'
                sh 'docker build -t ghcr.io/$GH_USER/jenkins-migration-auth-service:${GIT_COMMIT} ./backend/auth-service'
            }
        }
        stage('Unit test') {
            steps {
                echo 'Running unit test...'
                sh 'make auth-unit'
            }
        }
        stage('integration test') {
            steps {
                echo 'Running integration test...'
                sh 'make auth-integration'
            }
        }
        stage('login to GHCR') {
            steps {
                echo 'Logging in GHCR...'
                sh 'echo $CR_PAT | docker login ghcr.io -u $GH_USER --password-stdin'
            }
        }
        stage('push image') {
            steps {
                echo 'Pushing image to GHCR...'
                sh 'docker push ghcr.io/$GH_USER/jenkins-migration-auth-service:${GIT_COMMIT}'
            }
        }
        stage('Continuous Deployment') {
            steps {
                echo 'CD...'
                sh 'SHA=${GIT_COMMIT} docker compose -f docker-compose-prod.yml pull'
                sh 'SHA=${GIT_COMMIT} docker compose -f docker-compose-prod.yml up -d'
            }
        }
    }
    post {
        always {
        sh 'docker logout'
        }
    }
}