pipeline {
    agent any
    environment {
        CR_PAT = credentials('GHCR_TOKEN')
        GH_USER = 'almat101'
    }
    stages {        
        stage('build all') {
            docker {
                image 'docker:24.0.7-cli'
                args '-v /var/run/docker.sock:/var/run/docker.sock'
            }
            steps {
                checkout scm
                echo 'Building all images(with tag)...'
                sh 'docker build -t ghcr.io/$GH_USER/jenkins-migration-auth-service:${GIT_COMMIT} ./backend/auth-service'
                sh 'docker build -t ghcr.io/$GH_USER/jenkins-migration-products-service:${GIT_COMMIT} ./backend/products-service'
                sh 'docker build -t ghcr.io/$GH_USER/jenkins-migration-orders-service:${GIT_COMMIT} ./backend/orders-service'
                sh 'docker build -t ghcr.io/$GH_USER/jenkins-migration-frontend:${GIT_COMMIT} ./frontend'

            }
        }
        
        stage('integration test') {
            agent {
                docker { image 'node:24-alpine' }
            }
            steps {
                echo 'Checkout in every agent...'
                checkout scm
                echo 'Running integration test...'
                sh 'cd backend/auth-service && npm install && npm run test:integration'
            }
        }

        stage('Unit test') {
            agent { 
                docker { image 'node:24-alpine' }
            }
            steps {
                echo 'Checkout in every agent...'
                checkout scm
                echo 'Running unit test...'
                sh 'ls -l'
                sh 'cd backend/auth-service && npm install && npm run test:unit'
            }
        }

        stage('login to GHCR') {
            steps {
                echo 'Logging in GHCR...'
                sh 'echo $CR_PAT | docker login ghcr.io -u $GH_USER --password-stdin'
            }
        }

        stage('push auth-service') {
            docker {
                image 'docker:29-debian13-cli'
                args '-v /var/run/docker.sock:/var/run/docker.sock'
            }
            steps {
                checkout scm
                echo 'Pushing auth-service to GHCR...'
                sh 'docker push ghcr.io/$GH_USER/jenkins-migration-auth-service:${GIT_COMMIT}'
                sh 'docker push ghcr.io/$GH_USER/jenkins-migration-products-service:${GIT_COMMIT}'
                sh 'docker push ghcr.io/$GH_USER/jenkins-migration-orders-service:${GIT_COMMIT}'
                sh 'docker push ghcr.io/$GH_USER/jenkins-migration-frontend:${GIT_COMMIT}'
            }
        }
    }
}

    //    stage('build') {
    //         agent {
    //             docker { image 'docker/compose:alpine-1.29.2' }
    //             // docker { image 'docker/compose:debian-1.29.2' }
    //         }
    //         steps {
    //             echo 'Checkout in every agent...'
    //             checkout scm
    //             echo 'Checking compose version...'
    //             sh 'docker compose version'
    //             echo 'Building application...'
    //             sh 'docker compose build'
    //         }
    //     }